Train tutorial
myautoml/myautoml pull request #10
Opened 2021-06-08 08:29 UTC by EBolle

Hereby my train tutorial, fully re-written in reStructuredText and simplified. As far as I know I do not have permission to rebuild the documentation in read the docs so you have to take care of that. As mentioned on Slack you can find the 'live' version of this tutorial on [read the docs myautoml tutorial](https://myautoml-tutorial.readthedocs.io/en/latest/getting_started/tutorial.html), minus a few adjustments.

2021-06-14 03:08 UTC, erikjandevries requested changes
- In both of the MLflow images you can see your WIndows user folder ( `C:/Users/ernst` ). I don't have a real problem with it, but in general I prefer to keep personal info out.
- The training process highlighted image has a strange black spot at the top right.
- Does it make sense to keep the title "Training" in the training process highlighted image?
- I didn't see the `preview.csv` in the tutorial... Maybe you can add it? (If the file is not being used, I suggest removing it altogether.)

2021-06-15 19:14 UTC, EBolle commented
@erikjandevries I have made the suggested adjustments, plus a few extras when testing the tutorial again on the newly released version.

2021-06-17 08:26 UTC, erikjandevries requested changes
Zie comments.

2021-06-17 08:26 UTC, erikjandevries commented on cookiecutter/binary_classifier/{{cookiecutter.repo_name}}/scripts/environment.yml
> -  - python>=3.8
Laten we hier `>=3.8` houden, en in setup.py de requirements aanpassen (dus `,<3.9` verwijderen) - dat lijkt nu goed te gaan :-) (vroeger liep hij echt vast op 3.9, geloof ik).

2021-06-17 08:26 UTC, erikjandevries commented on docs/source/getting_started/train_tutorial.rst
> +You are now almost ready to run the train script. Make sure the ``.general.template`` part from the ``.env.general.template`` file is removed. This file
Beter is denk ik:

Make sure to make a copy of `.env.general.template` with the name `.env.general`. The template shows the settings that are (may be) expected by the program, without containing any secrets such as passwords, so that it can be committed to a git repository. You can update your personal and private settings in the `.env.general` file.
**Never commit your `.env.general` (with passwords, etc.) to a git repository!**

2021-06-19 04:50 UTC, erikjandevries approved these changes

2021-06-19 04:51 UTC, merged